name: Refresh Tencent Cloud CDN

on:
  push:
    branches: [ master ]

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
    - uses: keithnull/tencent-cloud-cdn-purge-cache@master
      env:
        SECRET_ID: ${{ secrets.SecretId}}
        SECRET_KEY: ${{ secrets.SecretKey }}
        PATHS: "https://www.imwzk.com/"
        FLUSH_TYPE: flush
